name: â¤´ï¸ Publish Package

on:
  push:
    tags: 
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    name: â¤´ï¸ Publish Package
    runs-on: ubuntu-latest
    environment: pub.dev
    permissions:
      id-token: write
    steps:
      - name: ğŸ“š Git Checkout
        uses: actions/checkout@v3
      
      - name: ğŸ¦ Setup Flutter
        uses: flutter-actions/setup-flutter@v4
      
      - name: ğŸ”‘ Setup pub.dev Credentials
        uses: flutter-actions/setup-pubdev-credentials@v1
      
      - name: ğŸ“¦ Install Dependencies
        run: flutter pub get

      - name: ğŸ“ Publish Package
        run: dart pub publish --force
